os: linux
jobs:
  include:
      - dist: jammy
        virt: vm
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: jammy
        virt: vm
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: jammy
        virt: vm
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: jammy
        virt: vm
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: jammy
        virt: vm
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: jammy
        virt: vm
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: jammy
        virt: vm
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: jammy
        virt: lxd
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: jammy
        virt: lxd
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: jammy
        virt: lxd
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: jammy
        virt: lxd
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: jammy
        virt: lxd
        language: ruby
        rvm: 
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        arch: amd64
        script:
          - ruby hello_world.rb
      - dist: jammy
        virt: lxd
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: jammy
        virt: lxd
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: bionic
        virt: vm
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: bionic
        virt: vm
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: bionic
        virt: vm
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: bionic
        virt: vm
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: bionic
        virt: vm
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: bionic
        virt: vm
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: bionic
        virt: vm
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: bionic
        virt: lxd
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: bionic
        virt: lxd
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: bionic
        virt: lxd
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: bionic
        virt: lxd
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: bionic
        virt: lxd
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: bionic
        virt: lxd
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: bionic
        virt: lxd
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: xenial
        virt: vm
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: xenial
        virt: vm
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: xenial
        virt: vm
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: xenial
        virt: vm
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: xenial
        virt: vm
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: xenial
        virt: vm
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: xenial
        virt: vm
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: xenial
        virt: lxd
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: xenial
        virt: lxd
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: xenial
        virt: lxd
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: xenial
        virt: lxd
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: xenial
        virt: lxd
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: xenial
        virt: lxd
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: xenial
        virt: lxd
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: focal
        virt: vm
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: focal
        virt: vm
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: focal
        virt: vm
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: focal
        virt: vm
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: focal
        virt: vm
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: focal
        virt: vm
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: focal
        virt: vm
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
      - dist: focal
        virt: lxd
        language: c
        arch: amd64
        script:
          - clang -coverage -O0 hello_world.c -o hello_world
          - ./hello_world
      - dist: focal
        virt: lxd
        language: python
        arch: amd64
        script:
          - python hello_world.py
      - dist: focal
        virt: lxd
        language: java
        arch: amd64
        script:
          - javac hello_world.java
          - java HelloWorld
      - dist: focal
        virt: lxd
        language: cpp
        arch: amd64
        script:
          - g++ hello_world.cpp -o hello_world
          - ./hello_world
      - dist: focal
        virt: lxd
        language: ruby
        arch: amd64
        rvm:
        - 2.5 # RVM should install 2.5.9 for RHEL 8
        - 2.6 # RVM should install 2.6.8 for RHEL 8
        - 2.7 # should use default pre-installed 2.7.4
        script:
          - ruby hello_world.rb
      - dist: focal
        virt: lxd
        language: node_js
        arch: amd64
        script:
          - node hello_world.js
      - dist: focal
        virt: lxd
        arch: amd64
        services:
          - mysql
          - postgresql
          - elasticsearch
          - mongodb
          - couchdb
        addons:
          mariadb: '10.0'
       - dist: jammy
         virt: vm
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: jammy
         virt: lxd
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: bionic
         virt: lxd
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: bionic
         virt: vm
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: xenial
         virt: lxd
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: xenial
         virt: vm
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: focal
         virt: lxd
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: focal
         virt: vm
         language: go
         go:
         - 1.x
         - "1.10"
         - 1.11.x
         - master
         arch: amd64
         script: 
           - go run hello_world.go
       - dist: jammy
         virt: vm
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: jammy
         virt: lxd
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: xenial
         virt: lxd
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: xenial
         virt: vm
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: bionic
         virt: lxd
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - nightly
         - hhvm # on Trusty only
         arch: amd64
         script:
           - php hello_world.php
       - dist: bionic
         virt: vm
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: focal
         virt: lxd
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: focal
         virt: vm
         language: php
         php:
         - '5.4'
         - '5.6'
         - '7.0'
         - hhvm # on Trusty only
         - nightly
         arch: amd64
         script:
           - php hello_world.php
       - dist: jammy
         virt: vm
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: jammy
         virt: lxd
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: xenial
         virt: vm  
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: xenial
         virt: lxd
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: bionic
         virt: vm
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: bionic
         virt: lxd
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: focal
         virt: vm
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: focal
         virt: lxd
         language: erlang
         otp_release:
           - "23.0.2"
           - "22.3.4"
         arch: amd64
       - dist: jammy
         virt: lxd
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: jammy
         virt: vm
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: xenial
         virt: vm
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: xenial
         virt: lxd
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: bionic
         virt: lxd
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: bionic
         virt: vm
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: focal
         virt: lxd
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: xenial
         virt: vm
         language: perl
         perl:
           - "5.30"
           - "5.28"
           - "5.26"
         arch: amd64
       - dist: jammy
         virt: vm
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: jammy
         virt: lxd
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: xenial
         virt: lxd
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: xenial
         virt: vm
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: bionic
         virt: lxd
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: bionic
         virt: vm
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: focal
         virt: lxd
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.py
       - dist: focal
         virt: vm
         language: python
         arch: amd64
         python:
             - "3.9-dev"  # 3.9 development branch
             - "nightly"  # nightly build
         before_install:
             - yum install -y rpm   
         script:
             - python hello_world.p
